manifest:
  defaults:
    revision: main

  remotes:
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos/
    - name: arribada
      url-base: https://github.com/arribada/

  projects:
    - name: zephyr
      remote: zephyr
      path: zephyr
      revision: v3.5.0
      import:
        name-allowlist:
          - cmsis
          - hal_nordic
          - nrf

    - name: custom-boards-zephyr
      remote: arribada
      path: modules/arribada-custom-boards
      revision: v3.6.0-add-linkit-board

  self:
    path: bma400-driver-zephyr
  
  